In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_firm = pd.read_csv("Firm Data.csv")

In [5]:
df_firm.head()

,RIC,Date,Total Current Assets,Total Current Liabilities,Total Debt,"Total Assets, Reported",Net Income - Actual,Revenue Per Share,Total Revenue,Total Equity,Total CO2 Equivalent Emissions To Revenues USD in million,ESG Score,Social Pillar Score,Governance Pillar Score,Environmental Pillar Score,Company Market Capitalization,"Property Plant And Equipment, Total - Gross",P/E (Daily Time Series Ratio)
0,BVIC.L,31/12/2009,434.373405,483.824655,718.957376,1361.504594,107.309409,7.068281,1561.383359,-3.988004,NaN,51.267135,45.539754,59.077651,53.535053,1430.561330,817.381317,19.299905
1,BVIC.L,31/12/2010,579.778906,580.095207,901.298414,1655.358922,139.656087,8.006665,1800.699024,-48.552134,NaN,50.550242,57.622888,31.890959,55.261467,1772.376566,889.120843,16.927900
2,BVIC.L,31/12/2011,598.968478,607.694345,893.154869,1660.096296,122.255528,7.912984,2010.689188,35.059289,NaN,46.732870,57.397993,28.924942,45.229496,1205.126197,836.280911,13.534436
3,BVIC.L,31/12/2012,615.523874,601.137943,907.121844,1658.099764,100.765756,7.914423,2030.840850,59.968319,NaN,57.941343,70.633040,37.216902,55.762859,1603.272359,872.046035,18.363571
4,BVIC.L,31/12/2013,748.229068,814.064189,895.874010,1714.940377,133.919162,8.716901,2133.025672,65.996482,31.296503,49.513243,52.778937,33.146107,58.148148,2819.919676,907.653333,27.421399

In [13]:
df_firm[df_firm['RIC'] == "0973.HK"]

,RIC,Date,Total Current Assets,Total Current Liabilities,Total Debt,"Total Assets, Reported",Net Income - Actual,Revenue Per Share,Total Revenue,Total Equity,Total CO2 Equivalent Emissions To Revenues USD in million,ESG Score,Social Pillar Score,Governance Pillar Score,Environmental Pillar Score,Company Market Capitalization,"Property Plant And Equipment, Total - Gross",P/E (Daily Time Series Ratio)
7748,0973.HK,31/12/2009,240.811949,188.057347,60.716370,464.325032,NaN,0.513582,654.487958,240.132170,NaN,NaN,NaN,NaN,NaN,NaN,166.753939,NaN
7749,0973.HK,31/12/2010,253.856442,280.511760,83.585296,589.835042,100.669684,0.649049,827.145733,212.499493,NaN,NaN,NaN,NaN,NaN,4017.068208,223.285913,31.188774
7750,0973.HK,31/12/2011,702.119070,209.480573,85.014944,1113.163449,142.107744,0.751724,1093.947335,793.611627,NaN,NaN,NaN,NaN,NaN,2917.111876,280.367438,22.840465
7751,0973.HK,31/12/2012,747.762389,220.512102,92.387853,1214.845355,152.357180,0.826429,1218.808209,867.547301,NaN,NaN,NaN,NaN,NaN,4579.518591,332.516745,27.606895
7752,0973.HK,31/12/2013,775.893097,227.765173,106.024483,1324.145357,164.015987,0.909489,1337.387682,934.865090,NaN,NaN,NaN,NaN,NaN,3090.301312,404.829840,21.740295
7753,0973.HK,31/12/2014,840.266035,287.871444,109.282311,1480.200215,121.041224,0.987497,1452.551568,1042.929140,NaN,NaN,NaN,NaN,NaN,3663.411805,472.516593,26.659649
7754,0973.HK,31/12/2015,770.856358,217.300986,118.218398,1297.630825,133.702599,0.858665,1263.857206,916.144296,NaN,NaN,NaN,NaN,NaN,2858.604839,428.742342,24.960643
7755,0973.HK,31/12/2016,810.574702,231.735485,101.125283,1352.095257,125.250289,0.992228,1459.427232,967.793467,13.675887,41.562442,37.614286,42.569444,48.232409,2796.178099,475.748956,22.603291
7756,0973.HK,31/12/2017,803.085000,225.186889,77.779908,1324.049581,147.738727,0.962542,1409.044151,979.575320,NaN,41.948172,36.642482,48.500000,45.712963,2707.182915,465.648627,19.082730
7757,0973.HK,31/12/2018,887.400508,289.198147,108.460856,1604.801508,113.476289,1.111981,1625.595722,1147.055272,NaN,52.875912,46.182279,54.041585,64.725636,2696.877730,549.064833,25.267266
7758,0973.HK,31/12/2019,623.072350,289.278744,648.278183,2203.040942,132.569826,1.091827,1600.531688,1141.635446,12.106656,51.411205,48.415760,42.310924,66.335963,3499.970717,568.916433,22.767031
7759,0973.HK,31/12/2020,609.956987,514.146906,988.950039,2656.180655,130.707670,1.238134,1813.260174,1211.514283,NaN,61.478096,62.911047,51.140926,69.028973,3647.666294,991.663174,28.072411
7760,0973.HK,31/12/2021,947.955809,1040.834565,957.991462,2919.732367,184.321044,1.226279,1803.585251,1398.960899,12.403595,62.435672,61.333245,53.411255,73.603698,5945.231893,353.330753,26.821584

In [7]:
df_return = pd.read_csv("yearly_return.csv")

In [8]:
df_return.head()

       RIC  Date  returns_monthly
0  0973.HK  2009         0.000000
1  0973.HK  2010        46.444961
2  0973.HK  2011       -23.899519
3  0973.HK  2012        51.000108
4  0973.HK  2013       -34.498730

In [16]:
df_firm

,RIC,Date,Total Current Assets,Total Current Liabilities,Total Debt,"Total Assets, Reported",Net Income - Actual,Revenue Per Share,Total Revenue,Total Equity,Total CO2 Equivalent Emissions To Revenues USD in million,ESG Score,Social Pillar Score,Governance Pillar Score,Environmental Pillar Score,Company Market Capitalization,"Property Plant And Equipment, Total - Gross",P/E (Daily Time Series Ratio)
0,BVIC.L,31/12/2009,434.373405,483.824655,718.957376,1361.504594,107.309409,7.068281,1561.383359,-3.988004,NaN,51.267135,45.539754,59.077651,53.535053,1430.561330,817.381317,19.299905
1,BVIC.L,31/12/2010,579.778906,580.095207,901.298414,1655.358922,139.656087,8.006665,1800.699024,-48.552134,NaN,50.550242,57.622888,31.890959,55.261467,1772.376566,889.120843,16.927900
2,BVIC.L,31/12/2011,598.968478,607.694345,893.154869,1660.096296,122.255528,7.912984,2010.689188,35.059289,NaN,46.732870,57.397993,28.924942,45.229496,1205.126197,836.280911,13.534436
3,BVIC.L,31/12/2012,615.523874,601.137943,907.121844,1658.099764,100.765756,7.914423,2030.840850,59.968319,NaN,57.941343,70.633040,37.216902,55.762859,1603.272359,872.046035,18.363571
4,BVIC.L,31/12/2013,748.229068,814.064189,895.874010,1714.940377,133.919162,8.716901,2133.025672,65.996482,31.296503,49.513243,52.778937,33.146107,58.148148,2819.919676,907.653333,27.421399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24474,AKSEN.IS,31/12/2017,418.425922,593.193096,686.553906,1177.461636,-96.256459,0.734857,901.182930,110.510293,NaN,NaN,NaN,NaN,NaN,2619.106333,923.520348,NaN
24475,AKSEN.IS,31/12/2018,388.901048,565.800430,644.077984,1372.966659,93.013406,0.774613,949.937152,423.188261,5241.540615,43.092015,45.157241,78.979592,20.402384,1217.855427,1228.850942,5.424041
24476,AKSEN.IS,31/12/2019,459.703083,534.734499,659.116542,1217.569452,4.765679,0.720062,883.039715,309.416385,4139.452613,36.847893,41.068317,61.910235,18.877956,1535.138199,1006.925461,12.342718
24477,AKSEN.IS,31/12/2020,451.245129,495.033610,533.871469,1429.264455,52.764679,0.764805,937.909982,586.836549,5443.698902,41.214852,56.987548,34.224871,33.265132,2405.441989,1271.610600,8.760031
24478,AKSEN.IS,31/12/2021,466.063443,443.711453,394.933054,1278.618718,64.085486,0.793332,972.893776,567.705256,3860.664870,59.201812,62.564203,69.491726,50.577681,901.334613,1131.160848,12.932008

In [23]:
df_firm['Date']=pd.to_datetime(df_firm['Date'])

In [29]:
df_firm['Date']=df_firm['Date'].dt.year

In [35]:
df_firm = df_firm.drop('Dates',axis=1)

In [36]:
df_firm

,RIC,Date,Total Current Assets,Total Current Liabilities,Total Debt,"Total Assets, Reported",Net Income - Actual,Revenue Per Share,Total Revenue,Total Equity,Total CO2 Equivalent Emissions To Revenues USD in million,ESG Score,Social Pillar Score,Governance Pillar Score,Environmental Pillar Score,Company Market Capitalization,"Property Plant And Equipment, Total - Gross",P/E (Daily Time Series Ratio)
0,BVIC.L,2009,434.373405,483.824655,718.957376,1361.504594,107.309409,7.068281,1561.383359,-3.988004,NaN,51.267135,45.539754,59.077651,53.535053,1430.561330,817.381317,19.299905
1,BVIC.L,2010,579.778906,580.095207,901.298414,1655.358922,139.656087,8.006665,1800.699024,-48.552134,NaN,50.550242,57.622888,31.890959,55.261467,1772.376566,889.120843,16.927900
2,BVIC.L,2011,598.968478,607.694345,893.154869,1660.096296,122.255528,7.912984,2010.689188,35.059289,NaN,46.732870,57.397993,28.924942,45.229496,1205.126197,836.280911,13.534436
3,BVIC.L,2012,615.523874,601.137943,907.121844,1658.099764,100.765756,7.914423,2030.840850,59.968319,NaN,57.941343,70.633040,37.216902,55.762859,1603.272359,872.046035,18.363571
4,BVIC.L,2013,748.229068,814.064189,895.874010,1714.940377,133.919162,8.716901,2133.025672,65.996482,31.296503,49.513243,52.778937,33.146107,58.148148,2819.919676,907.653333,27.421399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24474,AKSEN.IS,2017,418.425922,593.193096,686.553906,1177.461636,-96.256459,0.734857,901.182930,110.510293,NaN,NaN,NaN,NaN,NaN,2619.106333,923.520348,NaN
24475,AKSEN.IS,2018,388.901048,565.800430,644.077984,1372.966659,93.013406,0.774613,949.937152,423.188261,5241.540615,43.092015,45.157241,78.979592,20.402384,1217.855427,1228.850942,5.424041
24476,AKSEN.IS,2019,459.703083,534.734499,659.116542,1217.569452,4.765679,0.720062,883.039715,309.416385,4139.452613,36.847893,41.068317,61.910235,18.877956,1535.138199,1006.925461,12.342718
24477,AKSEN.IS,2020,451.245129,495.033610,533.871469,1429.264455,52.764679,0.764805,937.909982,586.836549,5443.698902,41.214852,56.987548,34.224871,33.265132,2405.441989,1271.610600,8.760031
24478,AKSEN.IS,2021,466.063443,443.711453,394.933054,1278.618718,64.085486,0.793332,972.893776,567.705256,3860.664870,59.201812,62.564203,69.491726,50.577681,901.334613,1131.160848,12.932008

In [37]:
df_merged = df_firm.merge(df_return, how="left", on=['RIC', 'Date'])

In [38]:
df_merged

,RIC,Date,Total Current Assets,Total Current Liabilities,Total Debt,"Total Assets, Reported",Net Income - Actual,Revenue Per Share,Total Revenue,Total Equity,Total CO2 Equivalent Emissions To Revenues USD in million,ESG Score,Social Pillar Score,Governance Pillar Score,Environmental Pillar Score,Company Market Capitalization,"Property Plant And Equipment, Total - Gross",P/E (Daily Time Series Ratio),returns_monthly
0,BVIC.L,2009,434.373405,483.824655,718.957376,1361.504594,107.309409,7.068281,1561.383359,-3.988004,NaN,51.267135,45.539754,59.077651,53.535053,1430.561330,817.381317,19.299905,48.651108
1,BVIC.L,2010,579.778906,580.095207,901.298414,1655.358922,139.656087,8.006665,1800.699024,-48.552134,NaN,50.550242,57.622888,31.890959,55.261467,1772.376566,889.120843,16.927900,15.557061
2,BVIC.L,2011,598.968478,607.694345,893.154869,1660.096296,122.255528,7.912984,2010.689188,35.059289,NaN,46.732870,57.397993,28.924942,45.229496,1205.126197,836.280911,13.534436,-33.927688
3,BVIC.L,2012,615.523874,601.137943,907.121844,1658.099764,100.765756,7.914423,2030.840850,59.968319,NaN,57.941343,70.633040,37.216902,55.762859,1603.272359,872.046035,18.363571,27.226920
4,BVIC.L,2013,748.229068,814.064189,895.874010,1714.940377,133.919162,8.716901,2133.025672,65.996482,31.296503,49.513243,52.778937,33.146107,58.148148,2819.919676,907.653333,27.421399,56.909555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24474,AKSEN.IS,2017,418.425922,593.193096,686.553906,1177.461636,-96.256459,0.734857,901.182930,110.510293,NaN,NaN,NaN,NaN,NaN,2619.106333,923.520348,NaN,37.755638
24475,AKSEN.IS,2018,388.901048,565.800430,644.077984,1372.966659,93.013406,0.774613,949.937152,423.188261,5241.540615,43.092015,45.157241,78.979592,20.402384,1217.855427,1228.850942,5.424041,-36.661598
24476,AKSEN.IS,2019,459.703083,534.734499,659.116542,1217.569452,4.765679,0.720062,883.039715,309.416385,4139.452613,36.847893,41.068317,61.910235,18.877956,1535.138199,1006.925461,12.342718,44.681008
24477,AKSEN.IS,2020,451.245129,495.033610,533.871469,1429.264455,52.764679,0.764805,937.909982,586.836549,5443.698902,41.214852,56.987548,34.224871,33.265132,2405.441989,1271.610600,8.760031,76.431919
24478,AKSEN.IS,2021,466.063443,443.711453,394.933054,1278.618718,64.085486,0.793332,972.893776,567.705256,3860.664870,59.201812,62.564203,69.491726,50.577681,901.334613,1131.160848,12.932008,68.939597

In [39]:
df_merged.to_csv('raw_data.csv', index=False)